### PR TITLE
Fix schema for report meetings and webinars

### PR DESCRIPTION
**Pull request by kekoav**
# Description of change
This is a fix for #3 . The exception was being thrown due to `dept` property being returned as a string but schema expected integer.

# Manual QA steps
Tested with my own zoom account and credentials.
 
# Risks
 - I'm not aware of any
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @kekoav, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @kekoav!

Thank you for signing the Singer Contribution License Agreement.

**Comment by kekoav** [comment]
@cmerrick let me know if you have any feedback here, would like to get this integration fixed.

**Comment by dmosorast** [comment]
Hi @kekoav! This looks to be a backwards incompatible change due to the change in data type, so we'll be including this in a 1.0.0 release of this tap, once we are able to gather up any other changes that need to be included. Thanks for the submission! If you see any other data type changes like this, we'd definitely like to wrap them all up into one release.

**Comment by allenjhyang** [comment]
Hi @dmosorast - do you have an expected timeline for the release of 1.0.0? Thanks!

**Comment by asaf-erlich** [comment]
I've pushed a local branch to get circle to run. It's green, will merge shortly hopefully, just double checking on the steps required for the 1.0.0 major version bump.

**Review by asaf-erlich — APPROVED** [review]

**Comment by asaf-erlich** [comment]
I've merged, I will report back when it's released.

**Comment by asaf-erlich** [comment]
Major version 1.0.0 has been released.

**Pull request merged**
